parameters:
  repositories: []

jobs:
- ${{ each repository in parameters.repositories}}:
  - deployment: test${{repository.job}}
    displayName: test ${{repository.name}}
    pool: 
      name: Windows
    environment: DEV
    strategy:
      runOnce:
        deploy:
          steps:
          - template: job.yml
            parameters:
              repository: ${{repository.name}}